language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
deploy:
  - provider: script
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
